print("what is your name?")
name= input()
print("what is your Department")
print("Software Developer")
print("CyberSecurity Specialist")
print("QA Tester")
print("(pick one)")
department=input()
print("what is your email")
email= input()
print("Enter your access")
access=input()
print("|---------------------------------------------------------|")
print("| Attendee: "+name.ljust(46) +"|")
print("| Dept: "+department.ljust(50)+"|")
print("| Contact: "+email.ljust(47)+"|")
print("| Access: "+access .ljust(48)+"|")
print("|---------------------------------------------------------|")
