print("what is your name?")
name= input()
print("what is your organization")
print("Software Developer")
print("CyberSecurity Specialist")
print("QA Tester")
organization=input()
print("what is your email")
email= input()
print("|------------------------------|")
print("| Attendee: "+name.ljust(19) +"|")
print("| Org: "+organization.ljust(24)+"|")
print("| Contact: "+email.ljust(20)+"|")